name:                calci
version:             0.1
github:              "satosystems/calci"
license:             BSD3
author:              "Satoshi Ogata"
maintainer:          "satosystems@gmail.com"
copyright:           "2018 Satoshi Ogata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            REPL calculator
category:            bsd3, compilers-interpreters, program

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/satosystems/calci#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline
- mtl
- parsec

library:
  source-dirs: src

executables:
  calci:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calci

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calci

